let lessons = [
    {
        id:1001,
        title:"Recipe",
        description:"Learn Cooking skills",
        price:500,
        image:"images/recipe.png",
        availableInventory:10,
        space:10,
        location:"Dubai",
        rating:3,
        },
    {
        id:1002,
        title:"Cars",
        description:"Be an expert in car collection",
        price:30000,
        image:"images/car.png",
        availableInventory:10,
        space:10,
        location: "USA",
        rating:2,
    },
    {
        id:1003,
        title:"kitchenWare",
        description:"Best tools for use in kitchen",
        price:1500,
        image:"images/utensil.png",
        availableInventory:10,
        space:10,
        location: "Ajman",
        rating:5,
    },
    {
        id:1004,
        title:"Socks",
        description:"All about keeping your legs warm",
        price:10,
        image:"images/socks.png",
        availableInventory:10,
        space:10,
        location: "Abu Dhabi",
        rating:1,
    },        
    {
        id:1005,
        title:"Chrismas Gift",
        description:"Special offer to get for your loved one",
        price:1000,
        image:"images/x-mas.png",
        availableInventory:10,
        space:10,
        location: "Silicon Oasis",
        rating:4,
    },
    {
        id:1006,
        title:"Flower",
        description:"Get your wifes something beutiful",
        price:1490,
        image:"images/flower.png",
        availableInventory:10,
        space:10,
        location: "Jumeirah",
        rating:3,
        },
    {
        id:1007,
        title:"English books",
        description:"Get good with communication skills",
        price:3200,
        image:"images/english.png",
        availableInventory:10,
        space:10,
        location: "Sharjah",
        rating:2,
    },
    {
        id:1008,
        title:"Business start up",
        description:"Learn how to get started with business",
        price:4000,
        image:"images/business.png",
        availableInventory:10,
        space:10,
        location: "Dubai",
        rating:5,
    },
    {
        id:1004,
        title:"Cyber Securityy",
        description:"Get started with cyber security skills",
        price:5000,
        image:"images/computer.png",
        availableInventory:10,
        space:10,
        location: "Dubai",
        rating:1,
    },        
    {
        id:1010,
        title:"Sports",
        description:"Get all material for sporting",
        price:2000,
        image:"images/addias.png",
        availableInventory:10,
        space:10,
        location: "Dubai",
        rating:4,
    }
]